#!/bin/bash

process_name="test"
log_file="/var/log/monitoring.log"
monitoring_url="https://test.com/monitoring/test/api"
unit_file="/etc/systemd/system/monitor-$process_name.service"
timer_file="/etc/systemd/system/monitor-$process_name.timer"

setup_monitoring() {
    sudo cp "$0" ~/scripts/monitor_$process_name.sh || true

    cat <<-EOF > "$unit_file"
    [Unit]
    Description=Monitoring script for $process_name
    After=network.target

    [Service]
    Type=oneshot
    ExecStart=/bin/bash \$HOME/scripts/monitor_$process_name.sh check
    User=root
    Group=root
    StandardOutput=null
    StandardError=inherit
    RemainAfterExit=yes

    [Install]
    WantedBy=multi-user.target
    EOF

    cat <<-EOF > "$timer_file"
    [Unit]
    Description=Periodic run of monitor-$process_name script

    [Timer]
    OnCalendar=*:*:00
    Persistent=true

    [Install]
    WantedBy=timers.target
    EOF

    sudo systemctl daemon-reload
    sudo systemctl enable monitor-$process_name.timer
    sudo systemctl start monitor-$process_name.timer
}

check_process() {
    if pgrep "$process_name" &>/dev/null; then
        if response=$(curl -s -o /dev/null -w '%{http_code}\n' "$monitoring_url"); then
            case $response in
                200|201)
                    echo "`date '+%Y-%m-%d %H:%M:%S'`: Процесс '$process_name' работает, мониторинг ответил $response." >> "$log_file"
                    ;;
                *)
                    echo "`date '+%Y-%m-%d %H:%M:%S'`: Сервер возвратил ошибку ($response) для процесса '$process_name'." >> "$log_file"
                    ;;
            esac
        else
            echo "`date '+%Y-%m-%d %H:%M:%S'`: Невозможно подключиться к серверу мониторинга для процесса '$process_name'." >> "$log_file"
        fi
    else
        return 0
    fi
}

case "$1" in
    setup)
        setup_monitoring
        ;;
    check)
        check_process
        ;;
    *)
        echo "Использование: $0 {setup|check}"  
        exit 1
        ;;
esac
